package example.sample05;

import java.util.HashMap;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;

/**
 * 
 * @param <APIGatewayProxyRequestEvent>  APIGatewayから渡されるリクエストを表すクラス
 * @param <APIGatewayProxyResponseEvent> APIGatewayへ渡すレスポンスを表すクラス
 */
public class ApiSample implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

	@Override
	public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent event, Context context) {

		// APIGatewayへ渡すレスポンスを作成
		APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();

		// Base64エンコード（文字種の制限）は無効
		response.setIsBase64Encoded(false);

		// APIのHTTPステータスコードは200（OK）を設定
		response.setStatusCode(200);

		// コンテンツタイプを設定
		HashMap<String, String> headers = new HashMap<String, String>();
		headers.put("Content-Type", "text/html");
		response.setHeaders(headers);

		// レスポンスボディの設定
		response.setBody("<!DOCTYPE html><html><head><title>Hello from AWS Lambda</title></head><body>"
				+ "<h1>Hello from AWS Lambda!</h1><p>This page is generated by a Lambda function.</p>" + "</body></html>");

		return response;
	}
}
